### ISSUE TITLE
Inconsistency for HashRouting with visible href & url in address bar

### ISSUE THREAD

**Issue by MoOx** [andreypopp/rrouter#17]
It's really nice to have this HashRouting thing.
But I've a small concern about the url we can have if we right click + new tab on the link
I've a route like this:

``` js
      <Route name="route-packages" path="packages" view={FcPackages}>
        <Route name="route-package" path=":package_id" view={FcPackage} />
      </Route>
```

![#packages in the address bar, but not when hovering](http://cl.ly/image/1v2x0a400z2j/Screen%20Shot%202014-05-28%20at%2019.45.49.png)

**Comment by andreypopp** [comment]
What's interesting is that this behaviour might be useful. Consider the case when your server can pre-render UI and so you can point a browser to `/packages` URL and get the needed page. From that point you will be navigating using `HashRouting` in browser and your URLs will look like `/packages#/someotherpage`.

Anyway, we should probably implement described above as a separate routing strategy (`PathnameWithHashFallbackRouting`?).

This issue should be fixed by moving `href` generation to routing strategy (`makeHref(name)` method), so that `HashRouting` could insert `#` at the start of the href.

**Comment by MoOx** [comment]
When I will (if I end up with that solution, for now not possible for my use case) use server side pre-render, it won't be necessary to use #hashRouting, just classic pushState will do the job don't you think ?
The case your are referring to seems a very specific/rare use case. 2 mains uses cases will be no hash routing (server side pre-render or transparent redirection to the index) or hash routing all the times.

**Comment by andreypopp** [comment]
You are right, fixed!

**Comment by MoOx** [comment]
![Well done !](https://dl.dropboxusercontent.com/u/14108185/memes/yeahyeahYEAH.gif)
