### ISSUE TITLE
Pass Routes props to children

### ISSUE THREAD

**Issue by mattatcha** [andreypopp/rrouter#20]
Should a child route include props from it's parent?

``` js
var routes = (
  <Routes flux={flux}>
       // Should the 'login' route have the 'flux' prop?
      <Route name="login" view={LoginPage}/>
  </Routes>
);
```

**Comment by andreypopp** [comment]
I considered adding this. Thanks for filing an issue.

**Comment by mattatcha** [comment]
This may be related https://github.com/facebook/react/issues/1061

**Comment by mattatcha** [comment]
What do you think about passing props from Routes to each child Route?

**Comment by andreypopp** [comment]
So I think I'm against the uncontrolled passing of props.

Given that we can configure separate isolated routes configurations by wrapping them in functions:

```
function UserRoutes(props) {
  return <Routes someProp={props.someProp}>...</Routes>
}
```

And that we now receive factories for subviews instead of subviews themselves we can inject additional props as needed:

```
render() {
  return <div>{this.props.subView({someProp: this.props.someProp})}</div>
}
```

We now have all use cases covered w/o leaking props around.

If you think there are more use cases, feel free to reopen.

**Comment by mattatcha** [comment]
Awesome! Just tested this out and it works really well! Thanks!
